name: Build, Test, and Release

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: test
        run: |
          go test -v ./...

      - name: Build
        run: |
          go build -o ytc-server .

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ytc-server
          path: ytc-server


  tag-and-release:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: ytc-server

      - name: Set up Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git fetch --tags

      - name: Get next semantic version
        id: semver
        uses: paulhatch/semantic-version@v5.4.0
        with:
          tag_prefix: "v"
          bump_each_commit: true

      - name: Create Git Tag
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git tag ${{ steps.semver.outputs.version }}
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }} ${{ steps.semver.outputs.version }}

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.semver.outputs.version }}
          name: Release ${{ steps.semver.outputs.version }}
          files: ytc-server
          body: |
            Automated release for version ${{ steps.semver.outputs.version }}.
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
